//console.log(document.domain);
console.dir(document);
document.title=123;
console.log(document.all);
console.log(document.getElementById('header-title'));
var headerTitle=document.getElementById('header-title');
headerTitle.style.fontWeight='bold';
//headerTitle.style.color='green';
var titles=document.getElementById('title');
titles.style.color='green';
titles.style.fontWeight='bold';